---
nodes:
  - name: node_0
    address: "127.0.0.1:20000"
    disks:
      - name: d1
        path: /bob/data/d1
vdisks:
  - id: 0
    replicas:
      - node: node_0
        disk: d1
  - id: 1
    replicas:
      - node: node_0
        disk: d1
