---
refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S):<20} {M:>20.30}:{L:>3} {h({l})}    {m}\n"
  requests:
    kind: rolling_file
    # [path] to the log file
    path: "/tmp/info.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S):<20} {M:>20.30}:{L:>3} {l} {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 20 mb
      roller:
        kind: fixed_window
        pattern: "./log/archive/info.{}.log"
        count: 10
    filters:
      - kind: threshold
        level: info
root:
  level: warn
  appenders:
    - stdout
    - requests
loggers:
  pearl:
    level: warn
    appenders:
      - stdout
      - requests
    additive: false
  bob:
    level: warn
    appenders:
      - stdout
      - requests
    additive: false
